function Grad = grad_boundary_matching_obj(...
    c, r, Index, pc_nosie, orientednormal_sampled, margin, scaling_alpha)

    h=1.0e-07;
    
    Grad(1) = (boundary_matching_obj(c + [h, 0], r, Index, pc_nosie, ...
        orientednormal_sampled, margin, scaling_alpha) - ...
        boundary_matching_obj(c - [h,0], r, Index, pc_nosie, ...
        orientednormal_sampled, margin, scaling_alpha))/(2*h);
    Grad(2) = (boundary_matching_obj(c + [0,h], r, Index, pc_nosie, ...
        orientednormal_sampled, margin, scaling_alpha) - ...
        boundary_matching_obj(c - [0, h], r, Index, pc_nosie, ...
        orientednormal_sampled, margin, scaling_alpha))/(2*h);
    Grad(3) = (boundary_matching_obj(c, r + h, Index, pc_nosie, ...
        orientednormal_sampled, margin, scaling_alpha) - ...
        boundary_matching_obj(c, r - h, Index, pc_nosie, ...
        orientednormal_sampled, margin, scaling_alpha))/(2*h);
end

