function Grad = grad_vol_max_obj(c, r, cost_prev, Index, pc_nosie, ...
    orientednormal_sampled, margin, scale_factor)
    h=1.0e-07;
    Grad(1) = (vol_max_obj(c + [h,0], r, cost_prev, Index, pc_nosie, ...
        orientednormal_sampled, margin, scale_factor) - vol_max_obj(c - [h, 0] , r, cost_prev, ... 
        Index, pc_nosie, orientednormal_sampled, margin, scale_factor))/(2*h);
    Grad(2) = (vol_max_obj(c + [0,h], r, cost_prev, Index, pc_nosie, ...
        orientednormal_sampled, margin, scale_factor) - vol_max_obj(c - [0, h], r, cost_prev, ...
        Index, pc_nosie, orientednormal_sampled, margin, scale_factor))/(2*h);
    Grad(3) = (vol_max_obj(c, r + h, cost_prev, Index, pc_nosie, ...
        orientednormal_sampled, margin, scale_factor) - vol_max_obj(c, r - h, cost_prev, ...
        Index, pc_nosie, orientednormal_sampled, margin, scale_factor))/(2*h);
end

