function cost = vol_max_obj(... 
    c, r, cost_prev,Index, pc_nosie, orientedNormal_sampled, ...
    margin, scale_factor)
    t= margin;
    cost = -0.02 * r ...
        + scale_factor * (max(distancefunc2d(c, pc_nosie, orientedNormal_sampled) + r, t)^2 ...
        + scale_factor * max(-r,0)^2 ...
        + scale_factor * max(boundary_matching_obj(c, r, Index,pc_nosie, ...
        orientedNormal_sampled, margin, scale_factor) - cost_prev, 0)^2);
end

